config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/admin', to: 'pages#admin'
  
  resources :families, except: [:new, :destroy]
  resources :subjects
  resources :members
  resources :parents
  resources :children
  resources :regs
  
  get '/register', to: 'families#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :parents, dependent: :destroy
  has_many :children, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :familyname, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: {case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:edit, :update, :show]
  before_action :require_user, only: [:index, :edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
    
  def index
    @families = Family.all
  end
  
  def new
    @family = Family.new
  end
  
  def create
    @family = Family.new(family_params)
    if @family.save
      flash[:success] = "Your Family has been created successfully"
      session[:family_id] = @family.id
      redirect_to family_path(current_user)
    else
      render 'pages/home' 
    end
  end

  def edit
    
  end
  
  def update
    if @family.update(family_params)
      flash[:success] = "Your Family has been updated successfully"
      redirect_to family_path
    end
  end

  def show

  end
  
  private
  def family_params
    params.require(:family).permit(:familyname, :email, :password, :active, :typemember)
  end

  def set_family
    @family = Family.find(params[:id])
  end
  
  def require_same_user
    if current_user != @family
      flash[:danger] = "You can only update your profile"
      redirect_to root_path
    end
  end
end

app/views/families/_form.html.erb
<% render 'shared/errors', obj: @family %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @family do |f| %>
      <%= f.label "Family Last Name" %>
      <%= f.text_field :familyname %>
      
      <% if current_user.admin? %>
        <%= f.label "Management System Admin" %>
        <%= f.check_box :admin %>
        
        <%= f.label "Active Member of NWACHEA" %>
        <%= f.check_box :active %>
        
        <%= f.label "How Involved" %>
        <%= f.select :typemember, [['Director', 'director'],['Teacher', 'teacher'],['Helper', 'helper']], include_blank: true %>
      <% end %>

      <%= f.label "Email Address" %>
      <%= f.email_field :email %>
      
      <%= f.label "Password" %>
      <%= f.password_field :password %>

      <%= f.submit(@family.new_record? ? 'Register Family' : 'Edit Family', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/families/edit.html.erb
<p>
  <h1>Edit Your Family</h1>
  <hr/>
</p>

<%= render 'form' %>

app/views/families/index.html.erb
<h1><center>All Families</center></h1>
<hr/>

<% @families.each do |family| %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 well">
      <h1> <%= link_to family.familyname, family_path(family) %></h1>
      <h2>Email: <%= mail_to family.email %></h2>
    </div>
  </div>
</div>  
<% end %>

app/views/families/new.html.erb
<p>
  <h1>Register New Family</h1>
  <hr/>
</p>

<%= render 'form' %>

app/views/families/show.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-2 pull-left center">
    </div>
    <div class="col-9-lg">
      <div class="well">
        <h1><%= @family.familyname + " Family" %></h1>  
        <h4>Email Address: <%= mail_to @family.email %>
                <% if current_user.admin? %>
          <h4>Active Member: <%= @family.active %></h4>
        <% end %>
        <%= link_to "Edit", edit_family_path, class: "btn btn-default pull-right" %></h4>
      </div>
    </div>
  </div>
</div>
<% @family.parents.each do |parent| %>
  <div class="row">
    <div class="container">
    <div class="well col-md-12">
      <h2> <%= link_to parent.firstname + " " + parent.lastname, parent_path(parent) %></h2>
        <h4>Phone: <%= parent.phone %></h4>
        <h4>Email Address: <%= mail_to @family.email %></h4>
    </div>
  </div>
</div>
<% end %>
<% @family.children.each do |child| %>
  <div class="row">
    <div class="container">
    <div class="well col-md-12">
      <h2><%= link_to child.firstname + " " + child.lastname, child_path(child) %></h2>
      <h4>Age: <%= child.age %></h4>
      <h4>Grade: <%= child.grade %></h4>
    </div>
  </div>
</div>
<% end %>