config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/admin', to: 'pages#admin'
  
  resources :families, except: [:new, :destroy]
  resources :subjects
  resources :members
  resources :parents
  resources :children
  resources :regs
  
  get '/register', to: 'families#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
end

app/views/pages/admin.html.erb
<h1>Admin</h1>
<div class="row">
  <div class="container">
    <div class="col-xs-3">
      <div class="well">
        <h2 style="color:white">Member Management</h2>
        <% @families.each do |family| %>
          <ul style="list-style: none;">
            <li> <%= link_to family.familyname, family_path(family) %></li>
          </ul>
        <% end %>  
      </div>
    </div>
    <div class="col-xs-3">
      <div class="well">
        <h2 style="color:white">Class Management</h2>
        <% @subjects.each do |subject| %>
          <ul style="list-style: none;">
            <li><%= link_to subject.subjectname, subject_path(subject) %></li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="col-xs-3">
      <div class="well">
        <h2 style="color:white"><center>Admin Placeholder</center></h2>
          <ul style="list-style: none;">
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "Logout", logout_path %></li>
            <li><%= link_to "All Familes", families_path %></li>
            <li><%= link_to "All Parents", parents_path %></li>
            <li><%= link_to "All Children", children_path %></li>
            <li><%= link_to "All Classes", subjects_path %></li>
            <li><%= link_to "Add Family", register_path %></li>
            <li><%= link_to "Add Parent", new_parent_path %></li>
            <li><%= link_to "Add Child", new_child_path %></li>
            <li><%= link_to "Add Class", new_subject_path %></li>
          </ul>
      </div>
    <div class="col-xs-3">
      <div class="well">
        <h2 style="color:white"><center>Admin Placeholder</center></h2>
          <ul style="list-style: none;">
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Logout", logout_path %></li>
          <li><%= link_to "All Familes", families_path %></li>
          <li><%= link_to "All Parents", parents_path %></li>
          <li><%= link_to "All Children", children_path %></li>
          <li><%= link_to "All Classes", subjects_path %></li>
          <li><%= link_to "Add Family", register_path %></li>
          <li><%= link_to "Add Parent", new_parent_path %></li>
          <li><%= link_to "Add Child", new_child_path %></li>
          <li><%= link_to "Add Class", new_subject_path %></li>
          </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  
  <% if @family.errors.any? %>
    <div class="row">
      <div class="alert alert-danger col-md-8 col-md-offset-2">
        <h5>Fix the following errors:</h5>
          <ul>
            <% @family.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
      </div>
    </div> 
  <% end %>
  
  <div class="well col-lg-4 pull-right">
      <h2><center>Login</center></h2>

      <%= form_tag '/login' do %>
    
      <%= label_tag 'Email' %>
      <%= text_field_tag :email %>
      
      <%= label_tag 'Password' %>
      <%= password_field_tag :password %>
      
      <%= submit_tag 'Login', class: 'btn btn-success' %>
      
    <% end %>
    
    <h3><center>Don't have an account?</center></h3>
    <center><%= link_to "Register", register_path, class: "btn btn-danger" %></center>

  </div>
  <div class="wellhome col-lg-8">
      <p align="left">
        <h1>Welcome to NWACHEA of Rogers' Member Management System.</h1>
        <h2>Using this system you will be able to:
        <ul style="list-style: none; "align="left">
          <li>Manage Your Family</li>
          <li>View Other Member's Info</li>
          <li>Register For Classes</li>
        </ul>
      </p>
      <p>
        We hope this system helps make your membership easier to manage.  If you have any suggestions please feel free to let us know!
      </p>
    </h2>
  </div>
</div>