config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/admin', to: 'pages#admin'
  
  resources :families, except: [:new, :destroy]
  resources :subjects
  resources :members
  resources :parents
  resources :children
  resources :regs
  
  get '/register', to: 'families#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  validates :subjectname, presence: true
  validates :grade, presence: true
  validates :hour, presence: true
  validates :cost, presence: true
  validates :teacher, presence: true
  validates :description, presence: true
  
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects = Subject.all
  end
  
  def show
    @subject = Subject.find(params[:id])
  end
  
  def new
    @subject = Subject.new
  end
  
  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:success] = "Class was created!"
      redirect_to subjects_path
    else
      render 'new'
    end
  end
  
  def destroy
    
  end
  
  private
  
  def subject_params
    params.require(:subject).permit(:subjectname, :grade, :hour, :cost, :teacher, :description)
  end
  

end

app/views/subjects/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @subject do |f| %>
      <%= f.label "Class Name" %>
      <%= f.text_field :subjectname %>

      <%= f.label "Grade" %>
      <%= f.select :grade, [['Nursery', 'nursery'],['Toddler', 'toddler'],['Pre-K', 'pre-k'],['K - 2', 'k-2'],['3 - 5', '3-5'],['6 - 8', '6-8'],['6 - 12', '6-12'],['9 - 12', '9-12']], include_blank: true %>
      
      <%= f.label "Hour" %>
      <%= f.select :hour, [['First', 'first'],['Second', 'second'],['Third', 'third']], include_blank: true %>
      
      <%= f.label "Cost" %>
      <%= f.text_field :cost %>

      <%= f.label "Teacher" %>
      <%= f.text_field :teacher %>
      
      <%= f.label "Class Description" %>
      <%= f.text_area :description %>

      <%= f.submit(@subject.new_record? ? 'Add Class' : 'Edit Class', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/subjects/edit.html.erb
<p>
  <h1>Edit Class</h1>
  <hr/>
</p>

<%= render 'form' %>

app/views/subjects/index.html.erb
<h1><center>All Classes</center></h1>
<hr/>

<% @subjects.each do |subject| %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 well">
      <h2><%= link_to subject.subjectname, subject_path(subject) %></h2>
      <h4>Grade: <%= subject.grade %></h4>
      <h4>Hour: <%= subject.hour %></h4>
      <h4>Cost: <%= subject.cost %></h4>
      <h4>Teacher: <%= subject.teacher %></h4>
      <h4>Description: <%= subject.description %></h4>
    </div>
  </div>
</div>  
<% end %>

app/views/subjects/new.html.erb
<%= render 'shared/errors', obj: @subject %>

<p>
  <h1>Add a Class</h1>
  <hr/>
</p>

<%= render 'form' %>

app/views/subjects/show.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-2 pull-left center">
    </div>
    <div class="col-12-lg">
      <div class="well">
        <h1><%= @subject.subjectname %></h1>  
        <h4>Grade: <%= @subject.grade %></h4>
        <h4>Hour: <%= @subject.hour %></h4>
        <h4>Cost: <%= @subject.cost %></h4>
        <h4>Teacher: <%= @subject.teacher %></h4>
        <h4>Description: <%= @subject.description %></h4>
        <%= link_to "Edit", edit_subject_path, class: "btn btn-default pull-right" %></h4>
      </div>
    </div>
  </div>
</div>
<% render 'shared/errors', obj: @subject %>