config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/admin', to: 'pages#admin'
  
  resources :families, except: [:new, :destroy]
  resources :subjects
  resources :members
  resources :parents
  resources :children
  resources :regs
  
  get '/register', to: 'families#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <p>&copy; NWACHEA of Rogers 2015</p>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<header>  
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" <%= link_to "NWACHEA of Rogers", home_path %></a>
      </div>
      <center>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Add Family Member </a>
          <ul class="dropdown-menu">
              <li><%= link_to "Add Parent", new_parent_path %></li>
              <li><%= link_to "Add Child", new_child_path %></li>
          </ul>
        </li>
        <% if current_user.active? %>
          <li class="active"><a href="#">Registry</a></li>
        <% end %>
        <% if current_user.admin? %>
        <li><%= link_to "Admin Area", admin_path %></li>
        <% end %>
        <% end %>
      <% if logged_in? %>
        <ul class="nav_item pull-right">
        <ul class="dropdown">
          <%=link_to '#', class: "btn btn-default dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.email %> <b class="caret"></b>
          <% end %>
        <ul class='dropdown-menu'>
          <li><%= link_to "View Profile", family_path(current_user) %></li>
          <li><%= link_to "Edit Profile", edit_family_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to "Logout", logout_path %></li>
        </ul>
      </li>
    </div>
            <% end %>
        </ul>
      </div>
      </center>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NWACHEA of Rogers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/nav" %>
  
  <div class="container">
    <%= render "layouts/messages" %>
    <%= yield %>
  </div>
        
<%= render "layouts/footer" %>

</body>
</html>